StrongTypes:

  - TypeName: "Distance"
    Wraps: "float"
    BinaryOperations:
      - Operation: "/"
        ArgType: "Time"
        ResType: "Velocity"

  - TypeName: "Time"
    Wraps: "float"

  - TypeName: "Velocity"
    Wraps: "float"
    BinaryOperations:
      - Operation: "+"
        ArgType: "Velocity"
        ResType: "Velocity"
      - Operation: "+="
        ArgType: "Velocity"
        ResType: "Velocity"
      - Operation: "/"
        ArgType: "float"
        ResType: "Velocity"
    UnaryOperations:
      - Operation: "-"
        ResType: "Velocity"