//
// Created by Beka Grdzelishvili (DerWaschbar) on 24.03.22.
//

#ifndef STRONGTYPETOOL_CONFIG_IN_H
#define STRONGTYPETOOL_CONFIG_IN_H

#cmakedefine CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
#cmakedefine CMAKE_INSTALL_DATADIR "${CMAKE_INSTALL_DATADIR}"
#cmakedefine RESOURCE_PATH "${RESOURCE_PATH}"
#cmakedefine CMAKE_CURRENT_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}"

#endif//STRONGTYPETOOL_CONFIG_IN_H
