name: TestCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install yaml-cpp
      run: sudo apt install libyaml-cpp-dev
    
    - name: Install nlohmann-json for inja
      run: git clone https://github.com/nlohmann/json.git &&
           cd json && mkdir build && cd build &&
           sudo cmake .. && sudo make && sudo make install
           
    - name: Install doctest for inja
      run: sudo apt install doctest-dev
      
    - name: Install hayai for inja
      run: git clone https://github.com/nickbruun/hayai.git &&
           cd hayai && mkdir build && cd build &&
           sudo cmake .. && sudo make && sudo make install
           
    - name: Install inja
      run: git clone https://github.com/pantor/inja.git &&
           cd inja && mkdir build && cd build && 
           sudo cmake .. && sudo make && sudo make install
           
    - name: Install boost
      run: sudo apt-get install libboost-all-dev
           
    - name: Install gtest
      run: git clone https://github.com/google/googletest.git &&
           cd googletest && mkdir build && cd build && 
           sudo cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr &&
           sudo make && sudo make install && sudo ldconfig            
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cd StrongTypeTool && cmake -B ${{github.workspace}}/StrongTypeTool/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cd StrongTypeTool && cmake --build ${{github.workspace}}/StrongTypeTool/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/StrongTypeTool/build
      run: ${{github.workspace}}/StrongTypeTool/build/tst/StrongTypeToolTest
      
